dist: focal

script:
  - cd project/$SERVICE
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/$SERVICE .
  - docker push $DOCKER_USERNAME/$SERVICE

jobs:
  include:
    - stage: build
      env: SERVICE=udagram-feed-api
    - env: SERVICE=udagram-user-api
    - env: SERVICE=udagram-frontend
    - env: SERVICE=udagram-reverse-proxy
    - stage: deploy
      install:
        # install aws cli
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
        # install kubectl
        - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        - aws eks update-kubeconfig --name udagram-eks
        - kubectl version
      script:
        - cd k8s
        - kubectl apply -f .
