dist: focal
python: 3.9

env:
  global:
    - DOCKER_BUILDKIT=1
  jobs:
    - SERVICE=udagram-feed-api
    - SERVICE=udagram-user-api
    - SERVICE=udagram-frontend
    - SERVICE=udagram-reverse-proxy

before_script:
  - cd project/$SERVICE
  - docker --version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t $DOCKER_USERNAME/$SERVICE .
  - docker push $DOCKER_USERNAME/$SERVICE

jobs:
  include:
    - stage: deploy
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
      script:
        - aws --version
