dist: focal

script:
  - cd project/$SERVICE
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/$SERVICE .
  - docker push $DOCKER_USERNAME/$SERVICE

jobs:
  include:
    - stage: build
      env: SERVICE=udagram-feed-api
    - env: SERVICE=udagram-user-api
    - env: SERVICE=udagram-frontend
    - env: SERVICE=udagram-reverse-proxy
    - stage: deploy
      python: 3.9
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
      script:
        - aws --version
