dist: bionic

addons:
  apt:
    packages:
      - docker-ce

env:
  - SERVICE=udagram-feed-api
  - SERVICE=udagram-user-api
  - SERVICE=udagram-frontend

before_script:
  - cd project/$SERVICE
  - docker --version

script:
  - docker build -t $DOCKER_USERNAME/$SERVICE .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/$SERVICE
