dist: bionic

env:
  - SERVICE=udagram-feed-api
  - SERVICE=udagram-user-api
  - SERVICE=udagram-frontend

before_script:
  - cd project/$SERVICE

script:
  - docker --version
  - DOCKER_BUILDKIT=1 docker build -t $DOCKER_USERNAME/$SERVICE .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/$SERVICE
