---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-user-api
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: udagram-user-api
    spec:
      containers:
        - name: udagram-user-api
          image: xistz/udagram-user-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: db_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: db_name
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: db_host
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: jwt_secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-user-api
spec:
  selector:
    app: udagram-user-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-user-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-user-api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
