---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feed-api
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: udagram-feed-api
    spec:
      containers:
        - name: udagram-feed-api
          image: xistz/udagram-feed-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-users-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-users-api
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: udagram-users-api
    spec:
      containers:
        - name: udagram-users-api
          image: xistz/udagram-users-api:latest
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
        - name: udagram-frontend
          image: xistz/udagram-frontend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
