---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feed-api
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: udagram-feed-api
    spec:
      containers:
        - name: udagram-feed-api
          image: xistz/udagram-feed-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: db_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: db_name
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: db_host
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: aws_region
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: aws_bucket
            - name: AWS_BUCKET_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: aws_bucket_access_key_id
            - name: AWS_BUCKET_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: aws_bucket_secret_access_key
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: jwt_secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api
spec:
  selector:
    app: udagram-feed-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
