version: '3.9'

x-api: &api-defaults
  env_file:
    - .env.dev

services:
  udagram-feed-api:
    build:
      context: ./udagram-feed-api
    <<: *api-defaults
  udagram-frontend:
    build:
      context: ./udagram-frontend
  udagram-user-api:
    build:
      context: ./udagram-user-api
    <<: *api-defaults
  udagram-reverse-proxy:
    build:
      context: ./udagram-reverse-proxy
    ports:
      - 8080:8080
    depends_on:
      - udagram-feed-api
      - udagram-user-api
      - udagram-frontend
